name: monitor
services:
  telegraf:
    image: telegraf:1.31.3
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: telegraf:${DOCKER_GROUP_ID}
    ports:
      - "9273:9273"
    profiles:
      - telegraf
      - monitor

  prometheus:
    image: prom/prometheus:v2.54.0
    hostname: prometheus
    command:
    # /!\ Change following Prometheus parameters as per your needs /!\
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1w'
      - '--storage.tsdb.retention.size=10GB'
    ports:
      - 9090:9090
    volumes:
      # /!\ To be modified depending on your needs /!\
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    profiles:
      - grafana-prometheus
      - monitor

  grafana:
    image: grafana/grafana:11.1.3
    hostname: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    profiles:
      - grafana-prometheus
      - monitor

volumes:
  grafana-storage:
  prometheus-storage:
