services:
  prometheus:
    image: prom/prometheus:v2.54.0
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./compose/monitor/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1w'
      - '--storage.tsdb.retention.size=10GB'

  grafana:
    image: grafana/grafana:11.1.3
    hostname: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      # Store sensitive data like admin username/password in a .env file
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  grafana-storage:
  prometheus-storage:
