services:
  telegraf:
    build:
      context: ./compose/telegraf
      dockerfile: Dockerfile
    hostname: telegraf
    volumes:
      - ./compose/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf    # Telegraf 설정 파일 마운트
      - ./compose/telegraf/docker_ps_info.sh:/app/docker_ps_info.sh                      
      - /var/run/docker.sock:/var/run/docker.sock:ro                    # Docker 소켓 마운트
      - /proc:/host/proc:ro                                             # 호스트의 /proc 디렉토리 마운트
      - /sys:/host/sys:ro                                               # 호스트의 /sys 디렉토리 마운트
      - /dev:/dev                                                       # 호스트의 /dev 디렉토리 마운트
    # user: root
    ports:
      - "9273:9273"  
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
    restart: unless-stopped