services:
  telegraf:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf     # Telegraf 설정 파일 마운트
      - ./scripts/:/app/
      - /var/run/docker.sock:/var/run/docker.sock       # Docker 소켓 파일 마운트
      - /proc:/host/proc:ro                             # 호스트의 /proc 디렉토리 마운트
      - /sys:/host/sys:ro                               # 호스트의 /sys 디렉토리 마운트
      - /dev:/dev                                       # 호스트의 /dev 디렉토리를 마운트하여 디스크 장치에 접근
    user: telegraf:${DOCKER_GROUP_ID}
    ports:
      - "9273:9273"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock                                     
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
    restart: unless-stopped
